name: PRs

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  e2e-tests-editor-extensions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - name: Install
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Tests
        run: npm run e2e:extensions
  e2e-tests-runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - name: Install
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Tests
        run: npm run e2e
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - name: Install
        run: npm ci
      - name: Unit tests
        run: npm test
      