name: PRs

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - name: Install
        run: npm ci
      - name: Unit tests
        run: npm test
      - name: Lint
        run: npm run lint
      - name: E2E runtime tests
        run: npm run e2e
      - name: E2E editor extension tests
        run: npm run e2e:extensions
